export const FETCH_QUEUE = 'FETCH_QUEUE'
export const FETCH_QUEUE_DETAIL = 'FETCH_QUEUE_DETAIL'
export const ADD_QUEUE = 'ADD_QUEUE'
export const LOGIN = 'LOGIN'
export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const FETCH_OUTLET = "FETCH_OUTLET";
export const LOGIN_ADMIN = "LOGIN_ADMIN";