export { default as Home } from './Home'
export { default as QRCode } from './QRCode'
export { default as QueueList } from './QueueList'
export { default as QueueHistory } from './QueueHistory'
export { default as AddOutlet } from './AddOutlet'
export { default as OutletList } from './OutletList'
